import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

interface Carts{
   
   Store s=new Store();
   ShoppingCart sc=new ShoppingCart();
   Delizia delizia=new Delizia();
   Hobnob h=new Hobnob();
   LaFarine lafarine=new LaFarine();
   DelFrio delfrio=new DelFrio();
   Payment p=new Payment();
   
}
interface deselecting{
    void DeSelect();
}

public class DelFrio  extends javax.swing.JFrame   implements Carts,deselecting {
    double total;
double totalPrice;
int qty;
int ln;
File f=new File("Admin");
  ArrayList<String> n= new ArrayList<String>();
   
    public DelFrio() {
        initComponents();
    }
    
   public void DeSelect(){
        ChocoFudge.setSelected(false);
        AlmondChocoDelight.setSelected(false);
        ChocoHeavenCake.setSelected(false);
        FreroRocherFudge.setSelected(false);
        ChocoMalt.setSelected(false);
        ChocoFudge_qty.setValue(0);
        AlmondChocoDelight_qty.setValue(0);
        ChocoHeavenCake_qty.setValue(0);
        FreroRocherFudge_qty.setValue(0);
        ChocoMalt_qty.setValue(0);
    }
    


    
    void cart(){
       
                        
            if(ChocoFudge.isSelected())   {
                
                qty=(int) ChocoFudge_qty.getValue();
               total=qty*1200;
                sc.addRow(new Object[]{"Choco Fudge",qty, 1200.0 ,total});
                
            }
            if(AlmondChocoDelight.isSelected())   {
                
                qty=(int)(AlmondChocoDelight_qty.getValue());
                total=qty*2300;
                sc.addRow(new Object[]{"Almond Choco Delight",qty, 2300.0 ,total});
                
            }
            if(ChocoHeavenCake.isSelected())   {
                
                qty=(int)ChocoHeavenCake_qty.getValue();
                total=qty*265;
                sc.addRow(new Object[]{"Choco Heaven Cake",qty, 265.0 ,total});
                
            }
            if(FreroRocherFudge.isSelected())   {
                
                qty=(int)FreroRocherFudge_qty.getValue();
                total=qty*2600;
                sc.addRow(new Object[]{"Frero Rocher Fudge",qty, 2600.0 ,total});
                
            }
            if(ChocoMalt.isSelected())   {
                
                qty=(int)ChocoMalt_qty.getValue();
                total=qty*1200;
                sc.addRow(new Object[]{"Choco Malt",qty, 1200.0 ,total});
               
            }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        FreroRocherFudge = new javax.swing.JRadioButton();
        AlmondChocoDelight = new javax.swing.JRadioButton();
        ChocoFudge = new javax.swing.JRadioButton();
        ChocoMalt = new javax.swing.JRadioButton();
        ChocoHeavenCake = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        AddToCart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ChocoHeavenCake_qty = new javax.swing.JSpinner();
        FreroRocherFudge_qty = new javax.swing.JSpinner();
        ChocoFudge_qty = new javax.swing.JSpinner();
        ChocoMalt_qty = new javax.swing.JSpinner();
        AlmondChocoDelight_qty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delfrio.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopping cart.jpg"))); // NOI18N
        cart.setBorder(null);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(221, 161, 80));
        back.setText("←");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cart))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FreroRocherFudge.setBackground(new java.awt.Color(0, 0, 0));
        FreroRocherFudge.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        FreroRocherFudge.setForeground(new java.awt.Color(221, 161, 80));
        FreroRocherFudge.setText("Frero Rocher Fudge");
        FreroRocherFudge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreroRocherFudgeActionPerformed(evt);
            }
        });
        jPanel2.add(FreroRocherFudge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        AlmondChocoDelight.setBackground(new java.awt.Color(0, 0, 0));
        AlmondChocoDelight.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        AlmondChocoDelight.setForeground(new java.awt.Color(221, 161, 80));
        AlmondChocoDelight.setText("Almond Choco Delight");
        AlmondChocoDelight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmondChocoDelightActionPerformed(evt);
            }
        });
        jPanel2.add(AlmondChocoDelight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        ChocoFudge.setBackground(new java.awt.Color(0, 0, 0));
        ChocoFudge.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChocoFudge.setForeground(new java.awt.Color(221, 161, 80));
        ChocoFudge.setText("Choco Fudge");
        ChocoFudge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocoFudgeActionPerformed(evt);
            }
        });
        jPanel2.add(ChocoFudge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        ChocoMalt.setBackground(new java.awt.Color(0, 0, 0));
        ChocoMalt.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChocoMalt.setForeground(new java.awt.Color(221, 161, 80));
        ChocoMalt.setText("Choco Malt");
        ChocoMalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocoMaltActionPerformed(evt);
            }
        });
        jPanel2.add(ChocoMalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        ChocoHeavenCake.setBackground(new java.awt.Color(0, 0, 0));
        ChocoHeavenCake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChocoHeavenCake.setForeground(new java.awt.Color(221, 161, 80));
        ChocoHeavenCake.setText("Choco Heaven Cake");
        ChocoHeavenCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocoHeavenCakeActionPerformed(evt);
            }
        });
        jPanel2.add(ChocoHeavenCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/df1 (3).jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 90));

        AddToCart.setBackground(new java.awt.Color(0, 0, 0));
        AddToCart.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        AddToCart.setForeground(new java.awt.Color(221, 161, 80));
        AddToCart.setText("ADD TO CART");
        AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartActionPerformed(evt);
            }
        });
        jPanel2.add(AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 170, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/df1 (5).jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/df1 (4).jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/df1 (2).jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/df1 (1).jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 90));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(221, 161, 80));
        jLabel9.setText("Rs. 1200");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 161, 80));
        jLabel10.setText("Rs. 2600");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 161, 80));
        jLabel11.setText("Rs. 1200");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(221, 161, 80));
        jLabel12.setText("Rs. 265");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 161, 80));
        jLabel13.setText("Rs. 2300");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        ChocoHeavenCake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChocoHeavenCake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChocoHeavenCake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChocoHeavenCake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 50, 30));

        FreroRocherFudge_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        FreroRocherFudge_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        FreroRocherFudge_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(FreroRocherFudge_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 50, 30));

        ChocoFudge_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChocoFudge_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChocoFudge_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChocoFudge_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 50, 30));

        ChocoMalt_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChocoMalt_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChocoMalt_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChocoMalt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 50, 30));

        AlmondChocoDelight_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        AlmondChocoDelight_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        AlmondChocoDelight_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(AlmondChocoDelight_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716 (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 810));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChocoFudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocoFudgeActionPerformed

    }//GEN-LAST:event_ChocoFudgeActionPerformed

    private void AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartActionPerformed
cart(); 
    }//GEN-LAST:event_AddToCartActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
dispose();
sc.setLocationRelativeTo(null);
sc.setVisible(true);
sc.Calculatetotalp();
DeSelect();

    }//GEN-LAST:event_cartActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       dispose();
       s.setLocationRelativeTo(null);
       s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void AlmondChocoDelightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmondChocoDelightActionPerformed
   
    }//GEN-LAST:event_AlmondChocoDelightActionPerformed

    private void ChocoHeavenCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocoHeavenCakeActionPerformed
  
    }//GEN-LAST:event_ChocoHeavenCakeActionPerformed

    private void FreroRocherFudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreroRocherFudgeActionPerformed
 
    }//GEN-LAST:event_FreroRocherFudgeActionPerformed

    private void ChocoMaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocoMaltActionPerformed
  
    }//GEN-LAST:event_ChocoMaltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelFrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelFrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelFrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelFrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelFrio().setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCart;
    private javax.swing.JRadioButton AlmondChocoDelight;
    private javax.swing.JSpinner AlmondChocoDelight_qty;
    private javax.swing.JRadioButton ChocoFudge;
    private javax.swing.JSpinner ChocoFudge_qty;
    private javax.swing.JRadioButton ChocoHeavenCake;
    private javax.swing.JSpinner ChocoHeavenCake_qty;
    private javax.swing.JRadioButton ChocoMalt;
    private javax.swing.JSpinner ChocoMalt_qty;
    private javax.swing.JRadioButton FreroRocherFudge;
    private javax.swing.JSpinner FreroRocherFudge_qty;
    private javax.swing.JButton back;
    private javax.swing.JButton cart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
