

public class Delizia extends javax.swing.JFrame implements Carts, deselecting {
double total;
int qty;
  

    /**
     * Creates new form Delizia
     */
    public Delizia() {
        initComponents();
    }
    
     public void DeSelect(){
        GalaxyChocolate.setSelected(false);
        SaltedCaramel.setSelected(false);
        CadburyBrownie.setSelected(false);
        ApplePieCup.setSelected(false);
        NutellaSundae.setSelected(false);
        GalaxyChocolate_qty.setValue(0);
        SaltedCaramel_qty.setValue(0);
        CadburyBrownie_qty.setValue(0);
        ApplePieCup_qty.setValue(0);
        NutellaSundae_qty.setValue(0);
    }
   
   
    void cart(){
   
    if(GalaxyChocolate.isSelected())   {
     qty=(int) GalaxyChocolate_qty.getValue();
     total=qty*1300;
     sc.addRow(new Object[]{"Galaxy Chocolate",qty, 1300.0 ,total});
}  
    if(SaltedCaramel.isSelected())   {
     qty=(int) SaltedCaramel_qty.getValue();
     total=qty*120;
    sc.addRow(new Object[]{"Salted Caramel",qty, 120.0 ,total});
}
   if(CadburyBrownie.isSelected())   {
     qty=(int) CadburyBrownie_qty.getValue();
     total=qty*80;
    sc.addRow(new Object[]{"Cadbury Brownie",qty, 80.0 ,total});
}
   if(ApplePieCup.isSelected())   {
    qty=(int) ApplePieCup_qty.getValue();
     total=qty*110;
    sc.addRow(new Object[]{"Apple Pie Cup",qty, 110.0 ,total});
} 
   if(NutellaSundae.isSelected())   {
    qty=(int)NutellaSundae_qty.getValue();
     total=qty*200;
     sc.addRow(new Object[]{"Nutella Sundae",qty, 200.0 ,total});
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CadburyBrownie = new javax.swing.JRadioButton();
        GalaxyChocolate = new javax.swing.JRadioButton();
        ApplePieCup = new javax.swing.JRadioButton();
        NutellaSundae = new javax.swing.JRadioButton();
        SaltedCaramel = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        GalaxyChocolate_qty = new javax.swing.JSpinner();
        CadburyBrownie_qty = new javax.swing.JSpinner();
        ApplePieCup_qty = new javax.swing.JSpinner();
        NutellaSundae_qty = new javax.swing.JSpinner();
        SaltedCaramel_qty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716_20200804225200293_20200804234345224.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopping cart.jpg"))); // NOI18N
        cart.setBorder(null);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        back1.setBackground(new java.awt.Color(0, 0, 0));
        back1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back1.setForeground(new java.awt.Color(221, 161, 80));
        back1.setText("←");
        back1.setBorder(null);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cart)
                                .addGap(3, 3, 3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CadburyBrownie.setBackground(new java.awt.Color(0, 0, 0));
        CadburyBrownie.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        CadburyBrownie.setForeground(new java.awt.Color(221, 161, 80));
        CadburyBrownie.setText("Cadbury Brownie");
        jPanel2.add(CadburyBrownie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        GalaxyChocolate.setBackground(new java.awt.Color(0, 0, 0));
        GalaxyChocolate.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        GalaxyChocolate.setForeground(new java.awt.Color(221, 161, 80));
        GalaxyChocolate.setText("Galaxy Chocolate ");
        jPanel2.add(GalaxyChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        ApplePieCup.setBackground(new java.awt.Color(0, 0, 0));
        ApplePieCup.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ApplePieCup.setForeground(new java.awt.Color(221, 161, 80));
        ApplePieCup.setText("Apple Pie Cup");
        ApplePieCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplePieCupActionPerformed(evt);
            }
        });
        jPanel2.add(ApplePieCup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        NutellaSundae.setBackground(new java.awt.Color(0, 0, 0));
        NutellaSundae.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        NutellaSundae.setForeground(new java.awt.Color(221, 161, 80));
        NutellaSundae.setText("Nutella Sundae");
        jPanel2.add(NutellaSundae, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        SaltedCaramel.setBackground(new java.awt.Color(0, 0, 0));
        SaltedCaramel.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        SaltedCaramel.setForeground(new java.awt.Color(221, 161, 80));
        SaltedCaramel.setText("Salted Caramel");
        jPanel2.add(SaltedCaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/D1.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 90));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 161, 80));
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 170, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716_20200806172932165_20200806174122316.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DELI.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716_20200806172932165_20200806174108103.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716_20200806172932165_20200806174040845.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 90));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(221, 161, 80));
        jLabel9.setText("Rs. 200");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 161, 80));
        jLabel10.setText("Rs. 80");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 161, 80));
        jLabel11.setText("Rs. 110");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(221, 161, 80));
        jLabel12.setText("Rs. 120");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 161, 80));
        jLabel13.setText("Rs. 1300");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        GalaxyChocolate_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        GalaxyChocolate_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        GalaxyChocolate_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(GalaxyChocolate_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, 30));

        CadburyBrownie_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CadburyBrownie_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CadburyBrownie_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(CadburyBrownie_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 50, 30));

        ApplePieCup_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ApplePieCup_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ApplePieCup_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ApplePieCup_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 50, 30));

        NutellaSundae_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        NutellaSundae_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        NutellaSundae_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(NutellaSundae_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 50, 30));

        SaltedCaramel_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SaltedCaramel_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        SaltedCaramel_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(SaltedCaramel_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716 (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 810));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
cart(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ApplePieCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplePieCupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApplePieCupActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
dispose();
sc.setLocationRelativeTo(null);
sc.setVisible(true);
sc.Calculatetotalp();
DeSelect();
    }//GEN-LAST:event_cartActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        dispose();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delizia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delizia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delizia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delizia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delizia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ApplePieCup;
    private javax.swing.JSpinner ApplePieCup_qty;
    private javax.swing.JRadioButton CadburyBrownie;
    private javax.swing.JSpinner CadburyBrownie_qty;
    private javax.swing.JRadioButton GalaxyChocolate;
    private javax.swing.JSpinner GalaxyChocolate_qty;
    private javax.swing.JRadioButton NutellaSundae;
    private javax.swing.JSpinner NutellaSundae_qty;
    private javax.swing.JRadioButton SaltedCaramel;
    private javax.swing.JSpinner SaltedCaramel_qty;
    private javax.swing.JButton back1;
    private javax.swing.JButton cart;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
