

public class Hobnob extends javax.swing.JFrame implements Carts, deselecting{
double total;
int qty;
  

    /**
     * Creates new form Hobnob
     */
    public Hobnob() {
        initComponents();
    }
     public void DeSelect(){
        GlazedDonut.setSelected(false);
        ChunkCookie.setSelected(false);
        FudgeCake.setSelected(false);
        ChocolateBrownie.setSelected(false);
        DoubleChocoCupcake.setSelected(false);
        GlazedDonut_qty.setValue(0);
        ChunkCookie_qty.setValue(0);
        FudgeCake_qty.setValue(0);
        ChocolateBrownie_qty.setValue(0);
        DoubleChocoCupcake_qty.setValue(0);
    }
    
    
    void cart(){
   
    if(GlazedDonut.isSelected())   {
      qty=(int) GlazedDonut_qty.getValue();
     total=qty*180;
     sc.addRow(new Object[]{"Glazed Donut",qty, 180.0 ,total});
}  
    if(ChunkCookie.isSelected())   {
      qty=(int) ChunkCookie_qty.getValue();
     total=qty*100;
     sc.addRow(new Object[]{"Chunk Cookie",qty, 100.0 ,total});
}
   if(FudgeCake.isSelected())   {
     qty=(int) FudgeCake_qty.getValue();
     total=qty*1750;
     sc.addRow(new Object[]{"Fudge Cake",qty, 1750.0 ,total});
}
   if(ChocolateBrownie.isSelected())   {
     qty=(int) ChocolateBrownie_qty.getValue();
     total=qty*130;
     sc.addRow(new Object[]{"Chocolate Brownie",qty, 130.0 ,total});
   } 
   if(DoubleChocoCupcake.isSelected())   {
     qty=(int) DoubleChocoCupcake_qty.getValue();
     total=qty*130;
     sc.addRow(new Object[]{"Double Choco Cupcake",qty, 130.0 ,total});
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        FudgeCake = new javax.swing.JRadioButton();
        GlazedDonut = new javax.swing.JRadioButton();
        ChocolateBrownie = new javax.swing.JRadioButton();
        DoubleChocoCupcake = new javax.swing.JRadioButton();
        ChunkCookie = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        GlazedDonut_qty = new javax.swing.JSpinner();
        FudgeCake_qty = new javax.swing.JSpinner();
        ChocolateBrownie_qty = new javax.swing.JSpinner();
        DoubleChocoCupcake_qty = new javax.swing.JSpinner();
        ChunkCookie_qty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hobnob logo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopping cart.jpg"))); // NOI18N
        cart.setBorder(null);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(221, 161, 80));
        back.setText("←");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cart))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FudgeCake.setBackground(new java.awt.Color(0, 0, 0));
        FudgeCake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        FudgeCake.setForeground(new java.awt.Color(221, 161, 80));
        FudgeCake.setText("Fudge Cake");
        FudgeCake.setActionCommand("");
        jPanel2.add(FudgeCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        GlazedDonut.setBackground(new java.awt.Color(0, 0, 0));
        GlazedDonut.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        GlazedDonut.setForeground(new java.awt.Color(221, 161, 80));
        GlazedDonut.setText("Glazed Donut");
        jPanel2.add(GlazedDonut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        ChocolateBrownie.setBackground(new java.awt.Color(0, 0, 0));
        ChocolateBrownie.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChocolateBrownie.setForeground(new java.awt.Color(221, 161, 80));
        ChocolateBrownie.setText("Chocolate Brownie");
        ChocolateBrownie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateBrownieActionPerformed(evt);
            }
        });
        jPanel2.add(ChocolateBrownie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        DoubleChocoCupcake.setBackground(new java.awt.Color(0, 0, 0));
        DoubleChocoCupcake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        DoubleChocoCupcake.setForeground(new java.awt.Color(221, 161, 80));
        DoubleChocoCupcake.setText("Double Choco Cupcake");
        DoubleChocoCupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleChocoCupcakeActionPerformed(evt);
            }
        });
        jPanel2.add(DoubleChocoCupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        ChunkCookie.setBackground(new java.awt.Color(0, 0, 0));
        ChunkCookie.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChunkCookie.setForeground(new java.awt.Color(221, 161, 80));
        ChunkCookie.setText("Chunk Cookie");
        jPanel2.add(ChunkCookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h3.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 90));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 161, 80));
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 170, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h5.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h4.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h2.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h1.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 90));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 161, 80));
        jLabel13.setText("Rs. 180");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(221, 161, 80));
        jLabel14.setText("Rs. 100");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(221, 161, 80));
        jLabel15.setText("Rs. 1750");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(221, 161, 80));
        jLabel16.setText("Rs. 130");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(221, 161, 80));
        jLabel17.setText("Rs. 130");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        GlazedDonut_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        GlazedDonut_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        GlazedDonut_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(GlazedDonut_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 50, 30));

        FudgeCake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        FudgeCake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        FudgeCake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(FudgeCake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 50, 30));

        ChocolateBrownie_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChocolateBrownie_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChocolateBrownie_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChocolateBrownie_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 50, 30));

        DoubleChocoCupcake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        DoubleChocoCupcake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        DoubleChocoCupcake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(DoubleChocoCupcake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 50, 30));

        ChunkCookie_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChunkCookie_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChunkCookie_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChunkCookie_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716 (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 810));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChocolateBrownieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateBrownieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChocolateBrownieActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
cart(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DoubleChocoCupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleChocoCupcakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleChocoCupcakeActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
dispose();
sc.setLocationRelativeTo(null);
sc.setVisible(true);
sc.Calculatetotalp();
DeSelect();
    }//GEN-LAST:event_cartActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        s.setLocationRelativeTo(null);
        s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hobnob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hobnob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hobnob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hobnob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hobnob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChocolateBrownie;
    private javax.swing.JSpinner ChocolateBrownie_qty;
    private javax.swing.JRadioButton ChunkCookie;
    private javax.swing.JSpinner ChunkCookie_qty;
    private javax.swing.JRadioButton DoubleChocoCupcake;
    private javax.swing.JSpinner DoubleChocoCupcake_qty;
    private javax.swing.JRadioButton FudgeCake;
    private javax.swing.JSpinner FudgeCake_qty;
    private javax.swing.JRadioButton GlazedDonut;
    private javax.swing.JSpinner GlazedDonut_qty;
    private javax.swing.JButton back;
    private javax.swing.JButton cart;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
