
public class LaFarine extends javax.swing.JFrame implements Carts, deselecting{
double total;
int qty;

    /**
     * Creates new form LaFarine
     */
    public LaFarine() {
        initComponents();
    }
    public void DeSelect(){
        HungarianCake.setSelected(false);
        
        
        NutellaCake.setSelected(false);
        ChocoFudgie.setSelected(false);
        HungarianCake_qty.setValue(0);
        
        LightChocoCake_qty.setValue(0);
        NutellaCake_qty.setValue(0);
        ChocoFudgie_qty.setValue(0);
    }
    
    
    void cart(){
   
    if(HungarianCake.isSelected())   {
     qty=(int) HungarianCake_qty.getValue();
     total=qty*3000;
     sc.addRow(new Object[]{"Hungarian Cake",qty, 3000.0 ,total});
     HungarianCake.setSelected(false);
     HungarianCake_qty.setValue(0);
     
}  
    if(DoubleChocoFudge.isSelected())   {
      qty=(int) DoubleChocoFudge_qty.getValue();
     total=qty*2400;
     sc.addRow(new Object[]{"Double Choco Fudge",qty, 2400.0 ,total});
     DoubleChocoFudge.setSelected(false);
     DoubleChocoFudge_qty.setValue(0);
}
   if(LightChocoCake.isSelected())   {
      qty=(int) LightChocoCake_qty.getValue();
     total=qty*2360;
     sc.addRow(new Object[]{"Light Choco Cake",qty, 2360.0 ,total});
}
   if(NutellaCake.isSelected())   {
     qty=(int) NutellaCake_qty.getValue();
     total=qty*2300;
     sc.addRow(new Object[]{"Nutella Cake",qty, 2300.0 ,total});
} 
   if(ChocoFudgie.isSelected())   {
     qty=(int) ChocoFudgie_qty.getValue();
     total=qty*2400;
     sc.addRow(new Object[]{"Choco Fudgie",qty, 2400.0 ,total});
}
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LightChocoCake = new javax.swing.JRadioButton();
        HungarianCake = new javax.swing.JRadioButton();
        NutellaCake = new javax.swing.JRadioButton();
        ChocoFudgie = new javax.swing.JRadioButton();
        DoubleChocoFudge = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        HungarianCake_qty = new javax.swing.JSpinner();
        LightChocoCake_qty = new javax.swing.JSpinner();
        NutellaCake_qty = new javax.swing.JSpinner();
        ChocoFudgie_qty = new javax.swing.JSpinner();
        DoubleChocoFudge_qty = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/La farine logo.jpg"))); // NOI18N
        jLabel14.setText("jLabel1");

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopping cart.jpg"))); // NOI18N
        cart.setBorder(null);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(221, 161, 80));
        back.setText("←");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cart)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(back, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LightChocoCake.setBackground(new java.awt.Color(0, 0, 0));
        LightChocoCake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        LightChocoCake.setForeground(new java.awt.Color(221, 161, 80));
        LightChocoCake.setText("Light Choco Cake");
        jPanel2.add(LightChocoCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        HungarianCake.setBackground(new java.awt.Color(0, 0, 0));
        HungarianCake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        HungarianCake.setForeground(new java.awt.Color(221, 161, 80));
        HungarianCake.setText("Hungarian Cake");
        jPanel2.add(HungarianCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        NutellaCake.setBackground(new java.awt.Color(0, 0, 0));
        NutellaCake.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        NutellaCake.setForeground(new java.awt.Color(221, 161, 80));
        NutellaCake.setText("Nutella Cake");
        NutellaCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutellaCakeActionPerformed(evt);
            }
        });
        jPanel2.add(NutellaCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        ChocoFudgie.setBackground(new java.awt.Color(0, 0, 0));
        ChocoFudgie.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        ChocoFudgie.setForeground(new java.awt.Color(221, 161, 80));
        ChocoFudgie.setText("Choco Fudgie");
        jPanel2.add(ChocoFudgie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        DoubleChocoFudge.setBackground(new java.awt.Color(0, 0, 0));
        DoubleChocoFudge.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        DoubleChocoFudge.setForeground(new java.awt.Color(221, 161, 80));
        DoubleChocoFudge.setText("Double Choco Fudge");
        jPanel2.add(DoubleChocoFudge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf3.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 90));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 161, 80));
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 170, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf5.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf4.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf2.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lf1.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 90));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(221, 161, 80));
        jLabel9.setText("Rs. 2400");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 161, 80));
        jLabel10.setText("Rs. 2360");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 161, 80));
        jLabel11.setText("Rs. 2300");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(221, 161, 80));
        jLabel12.setText("Rs. 2400");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 161, 80));
        jLabel13.setText("Rs. 3000");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        HungarianCake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        HungarianCake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        HungarianCake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(HungarianCake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, 30));

        LightChocoCake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        LightChocoCake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        LightChocoCake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(LightChocoCake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 50, 30));

        NutellaCake_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        NutellaCake_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        NutellaCake_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(NutellaCake_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 50, 30));

        ChocoFudgie_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ChocoFudgie_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        ChocoFudgie_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(ChocoFudgie_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 50, 30));

        DoubleChocoFudge_qty.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        DoubleChocoFudge_qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        DoubleChocoFudge_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 161, 80)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 161, 80))));
        jPanel2.add(DoubleChocoFudge_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 50, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716 (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 850));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716_20200804225200293_20200804234345224.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -40, 211, 68));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NutellaCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutellaCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NutellaCakeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
cart(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
dispose();
sc.setLocationRelativeTo(null);
sc.setVisible(true);
sc.Calculatetotalp();
DeSelect();
    }//GEN-LAST:event_cartActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        s.setLocationRelativeTo(null);
s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaFarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaFarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaFarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaFarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaFarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChocoFudgie;
    private javax.swing.JSpinner ChocoFudgie_qty;
    private javax.swing.JRadioButton DoubleChocoFudge;
    private javax.swing.JSpinner DoubleChocoFudge_qty;
    private javax.swing.JRadioButton HungarianCake;
    private javax.swing.JSpinner HungarianCake_qty;
    private javax.swing.JRadioButton LightChocoCake;
    private javax.swing.JSpinner LightChocoCake_qty;
    private javax.swing.JRadioButton NutellaCake;
    private javax.swing.JSpinner NutellaCake_qty;
    private javax.swing.JButton back;
    private javax.swing.JButton cart;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
