import java.awt.event.KeyEvent;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

interface Cstmdetail{
    Registeration r=new Registeration();
}

public class Registeration extends javax.swing.JFrame implements Cstmdetail{
    int line;
    File folder=new File("Information");
    int userid=(int) (Math.random()*100000);

    public Registeration() {
        initComponents();
    }
    public Registeration(String tfusername,String tfaddress){
        tfusername=this.tfusername.toString();
        tfaddress=this.tfaddress.toString();
    }
    void createFolder(){
        if(!folder.exists()){
            folder.mkdirs();
        }
    }
    
    void readFile(){
        try {
            FileReader fr=new FileReader(folder+"\\Customer.txt");
        } catch (FileNotFoundException ex) { 
            try {
                FileWriter fw=new FileWriter(folder+"\\Customer.txt");
            } catch (IOException ex1) {
                
            }
}
       }
   
    
    void addData(String tfusername,String tfpw,String tfnumber,String tfaddress,String tfemail){
        try {
            RandomAccessFile raf=new RandomAccessFile(folder+"\\Customer.txt","rw");
            for(int i=0;i<line;i++){
                raf.readLine();
            }
            boolean mail=false;
        
             if(!tfusername.equals("") && !tfpw.equals("") && !tfnumber.equals("") 
                     && !tfaddress.equals("") && !tfemail.equals("")){
                if(tfemail.contains("@")){
                mail=true;
                 raf.writeBytes("Username:"+ tfusername + "\r\n");
                 raf.writeBytes("Password:"+ tfpw+ "\r\n");
                 raf.writeBytes("Number:"+ tfnumber+ "\r\n");
                 raf.writeBytes("Address:"+ tfaddress+ "\r\n");
                 raf.writeBytes("Email:"+ tfemail+ "\r\n");
                 raf.writeBytes("User ID:" + userid + "\r\n");
                 raf.writeBytes("\r\n");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Invalid Email");
                mail=false;
            }
             }
                else{
                  JOptionPane.showMessageDialog(rootPane, "Please fill in the required fields");
                mail=false;
                        }
              
            if(mail==true){
                dispose();
                Login l1=new Login();
                l1.setLocationRelativeTo(null);
                l1.setVisible(true);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
    void countLine(){
        try {
            line=1;
            RandomAccessFile raf=new RandomAccessFile(folder+"\\Customer.txt","rw");
            for(int i=0;raf.readLine()!=null;i++){
                line++;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RegisterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfpw = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfnumber = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfemail = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfusername = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfaddress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 26, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(21, 26, 30));
        jTextField2.setFont(new java.awt.Font("Showcard Gothic", 0, 40)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(221, 161, 80));
        jTextField2.setText("Registeration");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterButton.setBackground(new java.awt.Color(0, 0, 0));
        RegisterButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(221, 161, 80));
        RegisterButton.setText("Register");
        RegisterButton.setActionCommand("");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 161, 80));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 161, 80));
        jLabel2.setText("Email:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        tfpw.setForeground(new java.awt.Color(221, 161, 80));
        tfpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpwActionPerformed(evt);
            }
        });
        jPanel2.add(tfpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, 30));

        jScrollPane2.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfnumber.setColumns(20);
        tfnumber.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tfnumber.setForeground(new java.awt.Color(221, 161, 80));
        tfnumber.setRows(5);
        tfnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnumberKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tfnumber);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(221, 161, 80));
        jLabel4.setText("Username:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jScrollPane3.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfemail.setColumns(20);
        tfemail.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tfemail.setForeground(new java.awt.Color(221, 161, 80));
        tfemail.setRows(5);
        jScrollPane3.setViewportView(tfemail);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 161, 80));
        jLabel5.setText("Mobile Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jScrollPane4.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfusername.setColumns(20);
        tfusername.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tfusername.setForeground(new java.awt.Color(221, 161, 80));
        tfusername.setRows(5);
        jScrollPane4.setViewportView(tfusername);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 170, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(221, 161, 80));
        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jScrollPane5.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfaddress.setColumns(20);
        tfaddress.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tfaddress.setForeground(new java.awt.Color(221, 161, 80));
        tfaddress.setRows(5);
        jScrollPane5.setViewportView(tfaddress);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSX_20200804_174950_20200804175745164.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
      createFolder();
      readFile();
     countLine();
      addData(tfusername.getText(), tfpw.getText() , tfnumber.getText(),tfaddress.getText(), tfemail.getText());
      
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void tfpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpwActionPerformed

    private void tfnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnumberKeyTyped
 char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfnumberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registeration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea tfaddress;
    private javax.swing.JTextArea tfemail;
    private javax.swing.JTextArea tfnumber;
    private javax.swing.JPasswordField tfpw;
    private javax.swing.JTextArea tfusername;
    // End of variables declaration//GEN-END:variables
}
