
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;



public class ShoppingCart extends javax.swing.JFrame implements Carts,deselecting {
    File f=new File("Admin");
   static DefaultTableModel model;
   int totalPrice;
   int line;
   Double total=new Double(0);
   int random= (int) (Math.random()*100000);
   
    public ShoppingCart() {
        initComponents();
        
       
    }
    public void DeSelect(){
    h.DeSelect();
    delizia.DeSelect();
    delfrio.DeSelect();
    lafarine.DeSelect();
}
    
    public void editted(){
         model=(DefaultTableModel) cart.getModel();
         
        if(cart.getSelectedRowCount()==1){
             int row=cart.getSelectedRow();
             total=total-((Double)(cart.getValueAt(row,3)));
             totalp.setText("Rs." + Double.toString(total));
             model.removeRow(cart.getSelectedRow());
        }
        else if(cart.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Shopping Cart is Empty.");
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
       
    
}
    public void Calculatetotalp(){
            total=0.0;
            for(int i=0;i<cart.getRowCount();i++){
               total+= (Double)(cart.getValueAt(i, 3));
                
            }
            totalp.setText("Rs." + Double.toString(total));
            orderID.setText(Integer.toString(random));
}

   
    
    public static void addRow(Object[] rows){
        model=(DefaultTableModel) cart.getModel();
        model.addRow(rows);
    }
    
    public void CalculateTotal(){
        try {
            countLine();
            RandomAccessFile view=new RandomAccessFile(f+"\\ViewOrders.txt","rw");
             for(int i=0;i<line;i++){
                view.readLine();
            }
            String a="";
             
            for(int i=0;i<cart.getRowCount();i++){
            a="Item:" + cart.getValueAt(i, 0) + ", Quantity:" +cart.getValueAt(i, 1).toString() + "\r\n";
            view.writeBytes(a);
            }
            view.writeBytes("Total Price:" + Double.toString(total) + "\r\n");
             view.writeBytes("Order Id:" + random + "\r\n");
             
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ShoppingCart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ShoppingCart.class.getName()).log(Level.SEVERE, null, ex);
        }
         
              
               
    }
    
     void countLine(){
        try {
            line=1;
            RandomAccessFile view=new RandomAccessFile(f+"\\ViewOrders.txt","rw");
            for(int i=0;view.readLine()!=null;i++){
                line++;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        Total1 = new javax.swing.JTextField();
        orderID = new javax.swing.JLabel();
        totalp = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 26, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(21, 26, 30));
        jTextField2.setFont(new java.awt.Font("Showcard Gothic", 0, 40)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(221, 161, 80));
        jTextField2.setText("shopping cart");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(221, 161, 80));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 80, 40));

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(221, 161, 80));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 90, 40));

        Checkout.setBackground(new java.awt.Color(0, 0, 0));
        Checkout.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Checkout.setForeground(new java.awt.Color(221, 161, 80));
        Checkout.setText("Checkout");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });
        jPanel2.add(Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 120, 40));

        Total.setEditable(false);
        Total.setBackground(new java.awt.Color(21, 26, 30));
        Total.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(221, 161, 80));
        Total.setText("Order Id:");
        Total.setBorder(null);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        jPanel2.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 30));
        Total.getAccessibleContext().setAccessibleName("TOTAL");

        cart.setBackground(new java.awt.Color(0, 0, 0));
        cart.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        cart.setForeground(new java.awt.Color(221, 161, 80));
        cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price / Unit", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cart);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 220));

        Total1.setEditable(false);
        Total1.setBackground(new java.awt.Color(21, 26, 30));
        Total1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Total1.setForeground(new java.awt.Color(221, 161, 80));
        Total1.setText("TOTAL:");
        Total1.setBorder(null);
        Total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total1ActionPerformed(evt);
            }
        });
        jPanel2.add(Total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 80, -1));

        orderID.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        orderID.setForeground(new java.awt.Color(221, 161, 80));
        jPanel2.add(orderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 90, 30));

        totalp.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        totalp.setForeground(new java.awt.Color(221, 161, 80));
        jPanel2.add(totalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 30));

        jlabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSX_20200804_174950_20200804175745164.jpg"))); // NOI18N
        jlabel1.setText("jLabel1");
        jPanel2.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, 400));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
dispose();
s.setLocationRelativeTo(null);
s.setVisible(true);
DeSelect();
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        editted();
    }//GEN-LAST:event_DeleteActionPerformed

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed
dispose();
sc.CalculateTotal();
p.setLocationRelativeTo(null);
p.setVisible(true);
    }//GEN-LAST:event_CheckoutActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void Total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        DelFrio delfrio = new DelFrio();
        Delizia delizia=new Delizia();
        Hobnob hobnob = new Hobnob();
        LaFarine lf=new LaFarine();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Checkout;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField Total1;
    private static javax.swing.JTable cart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel orderID;
    private javax.swing.JLabel totalp;
    // End of variables declaration//GEN-END:variables
}
