
import javax.swing.*;
/**
 *
 * @author Acer
 */


public class Store extends JFrame implements Carts{
    /**
     * Creates new form Store
     */
    public Store() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        Cart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        hobnob = new javax.swing.JButton();
        Delfrio = new javax.swing.JButton();
        Lafarine = new javax.swing.JButton();
        Delizia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(221, 161, 80));
        jTextField2.setText("Select Bakery Store");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopping cart.jpg"))); // NOI18N
        Cart.setBorder(null);
        Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cart))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hobnob.setBackground(new java.awt.Color(0, 0, 0));
        hobnob.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        hobnob.setForeground(new java.awt.Color(221, 161, 80));
        hobnob.setText("Hobnob");
        hobnob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobnobActionPerformed(evt);
            }
        });
        jPanel3.add(hobnob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, 50));

        Delfrio.setBackground(new java.awt.Color(0, 0, 0));
        Delfrio.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Delfrio.setForeground(new java.awt.Color(221, 161, 80));
        Delfrio.setText("Del Frio");
        Delfrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelfrioActionPerformed(evt);
            }
        });
        jPanel3.add(Delfrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 140, 50));

        Lafarine.setBackground(new java.awt.Color(0, 0, 0));
        Lafarine.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Lafarine.setForeground(new java.awt.Color(221, 161, 80));
        Lafarine.setText("La Farine");
        Lafarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LafarineActionPerformed(evt);
            }
        });
        jPanel3.add(Lafarine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 50));

        Delizia.setBackground(new java.awt.Color(0, 0, 0));
        Delizia.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Delizia.setForeground(new java.awt.Color(221, 161, 80));
        Delizia.setText("Delizia");
        Delizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliziaActionPerformed(evt);
            }
        });
        jPanel3.add(Delizia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20200804_223153_716 (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 1150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void DelfrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelfrioActionPerformed
dispose();
delfrio.setLocationRelativeTo(null);
delfrio.setVisible(true);
                         
    }//GEN-LAST:event_DelfrioActionPerformed

    private void DeliziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliziaActionPerformed
dispose();
delizia.setLocationRelativeTo(null);
delizia.setVisible(true);
    }//GEN-LAST:event_DeliziaActionPerformed

    private void CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartActionPerformed
dispose();
sc.setLocationRelativeTo(null);
sc.setVisible(true);
sc.Calculatetotalp();
    }//GEN-LAST:event_CartActionPerformed

    private void hobnobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobnobActionPerformed
dispose();
h.setLocationRelativeTo(null);
h.setVisible(true);                               
    }//GEN-LAST:event_hobnobActionPerformed

    private void LafarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LafarineActionPerformed
dispose();
lafarine.setLocationRelativeTo(null);
lafarine.setVisible(true);
                          
    }//GEN-LAST:event_LafarineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cart;
    private javax.swing.JButton Delfrio;
    private javax.swing.JButton Delizia;
    private javax.swing.JButton Lafarine;
    private javax.swing.JButton hobnob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
